name: 'Powershell Module Setup'
author: 'rulasg'
description: 'Setup a powershell module for later use on the workflow Job.'
branding:
  icon: "package"
  color: "orange"
inputs:
  Name:
    description: 'Name of the module to setup'
    required: true
  Version:
    description: 'Specifies which version of the module to use.'
    required: false
  AllowPreReleaseVersions:
    description: 'Allow the use of prerelease version of the module'
    default: 'true'
    required: false
#     AllowedSkippedTests:
#       description: 'Allow to use PreRelease versions onf the module module'
#       required: false
#     AllowedSkippedTests:
#       description: 'Allow tests to be skipped without failing'
#       required: false
#     AllowedNotImplementedTests:
#       description: 'Allow tests to be skipped without failing'
#       required: false
runs:
  using: "composite"
  steps:
    - name: Setup the module
      env:
        InputName: ${{ inputs.Name }}
        InputVersion: ${{ inputs.Version }}
        InputAllowPreReleaseVersions: ${{ inputs.AllowPreReleaseVersions }}
      shell: pwsh
      run: |

        $AllowPrerelease = ($env:InputAllowPreReleaseVersions -eq 'true')
        $Version = $env:InputVersion
        $Name = $env:InputName

        function Import-MyModule{
          [CmdletBinding()]
          param (
              [Parameter()][string]$Name,
              [Parameter()][string]$Version,
              [Parameter()][switch]$AllowPrerelease,
              [Parameter()][switch]$PassThru
          )
          
          if ($Version) {
              $V = $Version.Split('-')
              $semVer = $V[0]
              $AllowPrerelease = ($AllowPrerelease -or ($null -ne $V[1]))
          }
          
          $module = Import-Module $Name -PassThru -ErrorAction SilentlyContinue -RequiredVersion:$semVer
      
          if ($null -eq $module) {
              $installed = Install-Module -Name $Name -Force -AllowPrerelease:$AllowPrerelease -passThru -RequiredVersion:$Version
              $module = Import-Module -Name $installed.Name -RequiredVersion ($installed.Version.Split('-')[0]) -Force -PassThru
          }
      
          if ($PassThru) {
              $module
          }
        }

        Import-MyModule -AllowPrerelease:$AllowPrerelease -Version:$Version -Name $Name
